apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-go-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-go-web-app
  template:
    metadata:
      labels:
        app: my-go-web-app
    spec:
      containers:
        - name: webserver-simple
          image: docker.io/mklimko/my-go-web-app:b6dd6fe
          ports:
            - containerPort: 8080
